version: "3.8"

services:
  db:
    image: postgres:14
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pose_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      streamlit run app.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.headless=true
      --server.enableCORS=false

volumes:
  db_data:
